[package]
name = "http-server"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { version = "*", features = ["derive"] }
normalize-path = "*"
pathdiff = "*"
mime_guess = "*"
shared-string = "*"
tokio = { version = "*", features = ["full"] }
hyper = { version = "*", features = ["full"] }
http-body-util = "*"
hyper-util = { version = "*", features = ["full"] }
num_cpus = "*"
handlebars = "*"
serde = "*"
serde_json = "*"
chrono = "*"
unix_mode = "*"

[profile.release]
opt-level = 3
debug = false
lto = true
strip = "debuginfo"
panic = 'unwind'
incremental = false
codegen-units = 1
rpath = false
