[package]
name = "http-server"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { version = "*", features = ["derive"] }
normalize-path = "*"
pathdiff = "*"
mime_guess = "*"
tokio = { version = "*", features = ["rt-multi-thread"] }
hyper = { version = "*", features = ["http1"] }
http-body-util = "*"
hyper-util = { version = "*", features = ["server-graceful"] }
num_cpus = "*"
handlebars = "*"
serde_json = "*"
chrono = "*"
colored = "*"
tokio-util = { version = "*", features = ["io", "io-util", "futures-util"] }
futures = "*"
anyhow = "*"
notify-debouncer-full = "*"

[target.'cfg(unix)'.dependencies]
unix_mode = "*"

[profile.release]
opt-level = 3
debug = false
lto = true
strip = "debuginfo"
panic = 'unwind'
incremental = false
codegen-units = 1
rpath = false
